/*
 * SPDX-FileCopyrightText: 2021 Unisoc (Shanghai) Technologies Co., Ltd
 * SPDX-License-Identifier: GPL-2.0-only
*/

#ifndef __GPU_QOGIRN6L_MASK_H
#define __GPU_QOGIRN6L_MASK_H

#define MASK_GPU_DVFS_APB_RF_GPU_DVFS_ACK             0x100
#define MASK_GPU_DVFS_APB_RF_GPU_DVFS_VOLTAGE_SW      0x70
#define MASK_GPU_DVFS_APB_RF_GPU_DVFS_REQ_SW          0x1
#define MASK_GPU_DVFS_APB_RF_GPU_CORE_VOL_INDEX0      0x3c0
#define MASK_GPU_DVFS_APB_RF_GPU_CORE_VOL_INDEX1      0x3c0
#define MASK_GPU_DVFS_APB_RF_GPU_CORE_VOL_INDEX2      0x3c0
#define MASK_GPU_DVFS_APB_RF_GPU_CORE_VOL_INDEX3      0x3c0
#define MASK_GPU_DVFS_APB_RF_GPU_CORE_VOL_INDEX4      0x3c0
#define MASK_GPU_DVFS_APB_RF_GPU_CORE_VOL_INDEX5      0x3c0
#define MASK_GPU_DVFS_APB_RF_GPU_CORE_VOL_INDEX6      0x3c0
#define MASK_GPU_DVFS_APB_RF_GPU_CORE_VOL_INDEX7      0x3c0
#define MASK_GPU_DVFS_APB_RF_GPU_DVFS_INDEX           0x7
#define MASK_GPU_DVFS_APB_RF_GPU_INDEX6_MAP_SEL       0x7
#define MASK_GPU_DVFS_APB_RF_GPU_FREQ_UPD_DELAY_EN    0x2
#define MASK_GPU_DVFS_APB_RF_GPU_FREQ_UPD_HDSK_EN     0x1

#define MASK_GPU_APB_RF_BRIDGE_TRANS_IDLE_RO     0x2
#endif /* __GPU_QOGIRN6L_MASK_H */
