#SPDX-FileCopyrightText: 2020 Unisoc (Shanghai) Technologies Co.Ltd
#SPDX-License-Identifier: GPL-2.0-only

sprd-drm-y += \
	sysfs/sysfs_class.o \
	sysfs/sysfs_dpu.o \
	sysfs/sysfs_dphy.o \
	sysfs/sysfs_dsi.o \
	sysfs/sysfs_panel.o \
	sysfs/sysfs_backlight.o \
	sysfs/oplus_display_private_api.o
