#
# sprd_camera.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

#
# Source List
#
KO_MODULE_NAME := sprd_camera
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

ISP_DIR   := $(BSP_BOARD_CAMERA_MODULE_ISP_VERSION)
CSI_DIR   := $(BSP_BOARD_CAMERA_MODULE_CSI_VERSION)
ADAPT_DIR := $(BSP_BOARD_CAMERA_MODULE_ISP_ADAPT_VERSION)

ifeq ($(ISP_DIR),dcam_r6p0_isp_r6p91)
KO_MODULE_SRC += $(shell find $(KO_MODULE_PATH)/$(ISP_DIR) -name "*.c")
else
KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/$(ISP_DIR)/src/*.c)
  ifeq ($(ISP_DIR),dcam_if_r4p0_isp_r6p11)
  KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/common/*.c)
  endif
  KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/$(ISP_DIR)/block/*.c)
  ifeq ($(CONFIG_COMPAT),y)
  KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/$(ISP_DIR)/compat/*.c)
  endif
endif

ifeq ($(strip $(BSP_BUILD_VARIANT)),userdebug)
ccflags-y += -DCONFIG_SPRD_DCAM_DEBUG_RAW
endif

#
# Build Options
#
# target includes
ifeq ($(ISP_DIR),dcam_if_r4p0_isp_r6p11)
ccflags-y += -I$(KO_MODULE_PATH)/common
endif

ccflags-y += -I$(KO_MODULE_PATH)/../interface
ccflags-y += -I$(KO_MODULE_PATH)/../sensor
ccflags-y += -I$(KO_MODULE_PATH)/../sensor/csi2/sprd/$(CSI_DIR)
ccflags-y += -I$(KO_MODULE_PATH)/../flash/flash_drv
ccflags-y += -I$(KO_MODULE_PATH)/$(ISP_DIR)/inc
ccflags-y += -I$(KO_MODULE_PATH)/../os_adapt/linux
ccflags-y += -I$(srctree)/drivers/staging/android/ion

ifeq ($(ISP_DIR),dcam_r6p0_isp_r6p91)
ccflags-y += -I$(KO_MODULE_PATH)/$(ISP_DIR)/common
endif

ifeq ($(ISP_DIR), dcam_r6p0_isp_r6p91)
ccflags-y += -DPROJ_PIKE2
else ifeq ($(ISP_DIR), dcam_if_r4p0_isp_r6p11)
ccflags-y += -DPROJ_SHARKLE
endif

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
EXTRA_CFLAGS += -I$(KO_MODULE_PATH)/../power/kernel
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
