
# SPDX-FileCopyrightText: 2021-2023 Unisoc (Shanghai) Technologies Co. Ltd
# SPDX-License-Identifier: GPL-2.0-only
#
# unisoc_gnss_common_ctl_all.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

#
# Source List
#
KO_MODULE_NAME := unisoc_gnss_common_ctl_all

ifeq ($(strip $(BSP_KERNEL_VERSION)),kernel5.15)
KO_MODULE_PATH := $(src)
else
KO_MODULE_PATH := $(srctree)/$(src)
endif

#
# Build Options
#
ccflags-y += -I$(KO_MODULE_PATH)
ccflags-y += -I$(KO_MODULE_PATH)/../../../include

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o

#GNSS FILES
UNISOC_GNSS_COMMON_CTL := gnss_common_ctl.o

$(KO_MODULE_NAME)-y += $(UNISOC_GNSS_COMMON_CTL)

