# SPDX-FileCopyrightText: 2015 Spreadtrum Communications (Shanghai) Co., Ltd
# SPDX-FileCopyrightText: 2016 Unisoc (Shanghai) Technologies Co., Ltd
# SPDX-License-Identifier: GPL-2.0-only

#
# snd-soc-sprd-card.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please use these predefined name for keeping code:
#   KO_MODULE_NAME KO_MODULE_PATH KO_MODULE_SRC
#

#
# Source List
#
KO_MODULE_NAME := snd-soc-sprd-card
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

ccflags-y += -I$(KO_MODULE_PATH)/../../include
ccflags-y += -I$(KO_MODULE_PATH)/../../codec/sprd
ccflags-y += -I$(KO_MODULE_PATH)/../../../sprd_audio/agdsp_pd
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.sprd.arm.s9863a_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2721
ccflags-y += -DCONFIG_SND_SOC_UNISOC_SHARKL3
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.sprd.arm.sp7731e_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2721
ccflags-y += -DCONFIG_SND_SOC_UNISOC_PIKE2
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.sprd.arm.sp9832e_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2721
ccflags-y += -DCONFIG_SND_SOC_UNISOC_SHARKLE
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.s9863a_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2721
ccflags-y += -DCONFIG_SND_SOC_UNISOC_SHARKL3
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums312_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2730
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums512_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2730
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums9230_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2730
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums9620_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_UMP9620
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums9610_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_UMP9620
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums9621_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_UMP9620
endif

KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/*.c)

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o

SPRD_CARD_COMMON := \
		vbc-rxpx-codec-sc27xx.o \
		sprd-asoc-common.o \
		sprd-asoc-card-utils.o

ifeq ($(BSP_BOARD_AUDIO_EXTPA),true)
SPRD_CARD := \
		sprd-asoc-card-utils-hook_14c10.o \
		sprd-asoc-card-utils-legacy_14c10.o
else
SPRD_CARD := \
		sprd-asoc-card-utils-hook.o \
		sprd-asoc-card-utils-legacy.o
endif

$(KO_MODULE_NAME)-y += \
		$(SPRD_CARD_COMMON) \
		$(SPRD_CARD)

# Comment it if the only object file has the same name with module
# $(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
