#SPDX-FileCopyrightText: 2020 Unisoc (Shanghai) Technologies Co.Ltd
#SPDX-License-Identifier: GPL-2.0-only

sprd-drm-y += \
	qogirn6pro/global_dpu.o \
	qogirn6pro/global_dsi.o \
	qogirn6pro/global_dphy.o
