#
# snd_soc_akm4377.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please use these predefined name for keeping code:
#   KO_MODULE_NAME KO_MODULE_PATH KO_MODULE_SRC
#

#
# Source List
#
KO_MODULE_NAME := snd_soc_akm4377
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

ccflags-y += -I$(KO_MODULE_PATH)

ifeq ($(BSP_KERNEL_VERSION), kernel5.4)
ccflags-y += -DCONFIG_SND_SOC_AKM4377_K54
endif
ifeq ($(BSP_KERNEL_VERSION), kernel5.15)
#ccflags-y += -DCONFIG_SND_SOC_AKM4377_K515
endif

KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/*.c)

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))