# SPDX-FileCopyrightText: 2015 Spreadtrum Communications (Shanghai) Co., Ltd
# SPDX-FileCopyrightText: 2016 Unisoc (Shanghai) Technologies Co., Ltd
# SPDX-License-Identifier: GPL-2.0-only

#
# snd-soc-sprd-codec-ump9620.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please use these predefined name for keeping code:
#   KO_MODULE_NAME KO_MODULE_PATH KO_MODULE_SRC
#

#
# Source List
#
KO_MODULE_NAME := snd-soc-sprd-codec-ump9620
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

ccflags-y += -I$(KO_MODULE_PATH)
ccflags-y += -I$(KO_MODULE_PATH)/../include
ccflags-y += -I$(KO_MODULE_PATH)/../../
ccflags-y += -I$(KO_MODULE_PATH)/../../../../include
ccflags-y += -I$(KO_MODULE_PATH)/../../../../../sprd_audio/agdsp_pd

ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums9620_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_UMP9620
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums9610_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_UMP9620
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums9621_)
ccflags-y += -I$(KO_MODULE_PATH)/../../../../../../vender/audio/fsa4480
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_UMP9620
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_DNS_N6L
ccflags-y += -DCONFIG_SND_SOC_HEADSET_FSA4480
endif

KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/*.c)

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
