#SPDX-FileCopyrightText: 2020 Unisoc (Shanghai) Technologies Co.Ltd
#SPDX-License-Identifier: GPL-2.0-only


sprd-gsp-y += \
    gsp_interface/gsp_interface_qogirl6.o \
    gsp_interface/gsp_interface_qogirn6pro.o \
    gsp_interface/gsp_interface_sharkl5pro.o \
    gsp_interface/gsp_interface_pike2.o \
    gsp_interface/gsp_interface_qogirn6l.o \
    gsp_interface/gsp_interface_sharkle.o \
    gsp_interface/gsp_interface_sharkl5.o \
    gsp_interface/gsp_interface_sharkl3.o


