# SPDX-FileCopyrightText: 2015 Spreadtrum Communications (Shanghai) Co., Ltd
# SPDX-FileCopyrightText: 2016 Unisoc (Shanghai) Technologies Co., Ltd
# SPDX-License-Identifier: GPL-2.0-only

#
# snd-soc-sprd-vbc-r1p0v3.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please use these predefined name for keeping code:
#   KO_MODULE_NAME KO_MODULE_PATH KO_MODULE_SRC
#

#
# Source List
#
KO_MODULE_NAME := snd-soc-sprd-vbc-r1p0v3
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

ccflags-y += -I$(KO_MODULE_PATH)
ccflags-y += -I$(KO_MODULE_PATH)/../../../include
ccflags-y += -I$(KO_MODULE_PATH)/../../../platform/include
ccflags-y += -I$(KO_MODULE_PATH)/../../../platform/dmaengine_2stage_pcm

ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.sprd.arm.s9863a_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_SHARKL3
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.sprd.arm.sp7731e_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_PIKE2
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.sprd.arm.sp9832e_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_SHARKLE
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.s9863a_)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_SHARKL3
endif

KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/*.c)

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
