#
# sprdbt_tty.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#


#
# Source List
#
KO_MODULE_NAME := sprdbt_tty

ifeq ($(strip $(BSP_KERNEL_VERSION)),kernel5.15)
KO_MODULE_PATH := $(src)
else
KO_MODULE_PATH := $(srctree)/$(src)
endif

KO_MODULE_SRC  :=

KO_MODULE_SRC += \
	$(wildcard $(KO_MODULE_PATH)/tty-515/*.c) \
	$(wildcard $(KO_MODULE_PATH)/tty-515/alignment/*.c)

#
# Build Options
#
ccflags-y += -DDEBUG
ccflags-y += -I$(KO_MODULE_PATH)/../../include

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(KO_MODULE_PATH)/%.c,%.o,$(KO_MODULE_SRC))
