#
# flash_ic_aw3641.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

#
# Source List
#
KO_MODULE_NAME := flash_ic_aw3641
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

ISP_DIR   := $(BSP_BOARD_CAMERA_MODULE_ISP_VERSION)
KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/*.c)

#
# Build Options
#
ccflags-y += -I$(KO_MODULE_PATH)/../flash_drv
ccflags-y += -I$(KO_MODULE_PATH)/../../interface
ccflags-y += -I$(KO_MODULE_PATH)/../../interface/cam_sys

ifeq ($(ISP_DIR), dcam_r6p0_isp_r6p91)
ccflags-y += -DPROJ_PIKE2
else ifeq ($(ISP_DIR), dcam_if_r4p0_isp_r6p11)
ccflags-y += -DPROJ_SHARKLE
endif

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
