#SPDX-FileCopyrightText: 2020 Unisoc (Shanghai) Technologies Co.Ltd
#SPDX-License-Identifier: GPL-2.0-only

sprd-drm-y += \
	dsi/core/dsi_ctrl_r1p0.o \
	dsi/core/dsi_ctrl_r1p1.o \
	dsi/core/dsi_ctrl_r1p0_ppi.o \
	dsi/core/dsi_ctrl_r1p1_ppi.o
