# SPDX-FileCopyrightText: 2015 Spreadtrum Communications (Shanghai) Co., Ltd
# SPDX-FileCopyrightText: 2016 Unisoc (Shanghai) Technologies Co., Ltd
# SPDX-License-Identifier: GPL-2.0-only

#
# snd-soc-sprd-vbc-v4.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please use these predefined name for keeping code:
#   KO_MODULE_NAME KO_MODULE_PATH KO_MODULE_SRC
#

#
# Source List
#
KO_MODULE_NAME := snd-soc-sprd-vbc-v4
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

ccflags-y += -I$(KO_MODULE_PATH)
ccflags-y += -I$(KO_MODULE_PATH)/../../../../include
ccflags-y += -I$(KO_MODULE_PATH)/../../../../platform/include
ccflags-y += -I$(KO_MODULE_PATH)/../../../../platform/platform_routing
ccflags-y += -I$(KO_MODULE_PATH)/../../../../platform/dmaengine_pcm
ccflags-y += -I$(KO_MODULE_PATH)/../../../../../sprd_audio/audiomem
ccflags-y += -I$(KO_MODULE_PATH)/../../../../../sprd_audio/audiosipc
ccflags-y += -I$(KO_MODULE_PATH)/../../../../../sprd_audio/agdsp_pd
ccflags-y += -I$(KO_MODULE_PATH)/../../../../../sprd_audio/mcdt
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums312_)
ccflags-y += -DCONFIG_UNISOC_AUDIO_MCDT
ccflags-y += -DCONFIG_UNISOC_AUDIO_VBC_FM_UNMUTE_SMOOTH_NOT_SUPPORT
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums512_)
ccflags-y += -DCONFIG_UNISOC_AUDIO_MCDT
ccflags-y += -DCONFIG_UNISOC_AUDIO_VBC_FM_UNMUTE_SMOOTH_NOT_SUPPORT
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums9230_)
ccflags-y += -DCONFIG_UNISOC_AUDIO_MCDT_R2P0
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums9620_)
ccflags-y += -DCONFIG_UNISOC_AUDIO_MCDT_R2P0
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums9610_)
ccflags-y += -DCONFIG_UNISOC_AUDIO_MCDT_R2P0
endif
ifeq ($(BSP_KERNEL_BUILD_CONFIG),build.config.gki.aarch64.ums9621_)
ccflags-y += -DCONFIG_UNISOC_AUDIO_MCDT_R2P0
endif

KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/*.c)

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
