#SPDX-FileCopyrightText: 2019 Unisoc (Shanghai) Technologies Co.Ltd
#SPDX-License-Identifier: GPL-2.0-only
#
# Configurations
#
CONFIG_UNISOC_VPU := m

#
# Source List
#
vpu-y := \
	sprd_vpu.o \
	common_drv.o \
	vpu_r1p0.o \
	vsp_hevc_lite.o \
	vsp_1080p_r1p0.o \
	vsp_hevc_lite_r1p0.o

#
# Build Options
#

ccflags-y += -I$(srctree)/drivers/devfreq/apsys/

#
# Final Objects
#
obj-$(CONFIG_UNISOC_VPU) := vpu.o
KO_MODULE_PATH := $(src)

ADAPT_DIR := $(BSP_BOARD_CAMERA_MODULE_VSP_ADAPT_VERSION)
ifeq ($(ADAPT_DIR), pike2)
ccflags-y += -DPROJ_PIKE2
endif
EXTRA_CFLAGS += -I$(KO_MODULE_PATH)/../../../common/camera/power/kernel/
