/*
*SPDX-FileCopyrightText:2023 Unisoc (Shanghai) Technologies Co.Ltd
*SPDX-License-Identifier:GPL-2.0-only
*/
{ /*sharkle || PIKE2*/
	.mmu_vaor_addr_rd = 0x158,
	.mmu_vaor_addr_wr = 0x15C,
	.mmu_inv_addr_rd = 0x160,
	.mmu_inv_addr_wr = 0x164,
	.mmu_uns_addr_rd = 0x168,
	.mmu_uns_addr_wr = 0x16C,
	.mmu_vpn_paor_rd = 0x18C,
	.mmu_vpn_paor_wr = 0x190,
	.mmu_ppn_paor_rd = 0x194,
	.mmu_ppn_paor_wr = 0x198,
	.mmu_int_en_off = 0x0,
	.mmu_int_clr_off = 0x0,
	.mmu_int_raw_off = 0x0,
	.mmu_int_msk_off = 0x0,
	.mmu_en_off = 0x140,
	.mmu_update_off = 0x144,
},
{ /*SHARKL3 || SHARKL5*/
	.mmu_vaor_addr_rd = 0x18,
	.mmu_vaor_addr_wr = 0x1C,
	.mmu_inv_addr_rd = 0x20,
	.mmu_inv_addr_wr = 0x24,
	.mmu_uns_addr_rd = 0x28,
	.mmu_uns_addr_wr = 0x2C,
	.mmu_vpn_paor_rd = 0x4C,
	.mmu_vpn_paor_wr = 0x50,
	.mmu_ppn_paor_rd = 0x54,
	.mmu_ppn_paor_wr = 0x58,
	.mmu_int_en_off = 0x60,
	.mmu_int_clr_off = 0x64,
	.mmu_int_raw_off = 0x68,
	.mmu_int_msk_off = 0x6C,
	.mmu_en_off = 0x00,
	.mmu_update_off = 0x04,
},
{ /*SHARKL5PRO || SHARKL6 || QOGIRN6PRO || QOGIRN6L*/
	.mmu_vaor_addr_rd = 0x54,
	.mmu_vaor_addr_wr = 0x58,
	.mmu_inv_addr_rd = 0x5C,
	.mmu_inv_addr_wr = 0x60,
	.mmu_uns_addr_rd = 0x64,
	.mmu_uns_addr_wr = 0x68,
	.mmu_vpn_paor_rd = 0x44,
	.mmu_vpn_paor_wr = 0x48,
	.mmu_ppn_paor_rd = 0x4C,
	.mmu_ppn_paor_wr = 0x50,
	.mmu_int_en_off = 0xA0,
	.mmu_int_clr_off = 0xA4,
	.mmu_int_sts_off = 0xA8,
	.mmu_int_raw_off = 0xAC,
	.mmu_en_off = 0x04,
	.mmu_update_off = 0x08,
},

